// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRC7HV2jcyhPAvMuwbHv0zLNTg2QYakWA',
    appId: '1:8552136043:web:8089a2aacb0134dad3a02e',
    messagingSenderId: '8552136043',
    projectId: 'fir-demo-project-f6869',
    authDomain: 'fir-demo-project-f6869.firebaseapp.com',
    storageBucket: 'fir-demo-project-f6869.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuMBuAua3Vz4vE4uCTsT5NTfXo0alGcfM',
    appId: '1:8552136043:android:16ac008b586c3e84d3a02e',
    messagingSenderId: '8552136043',
    projectId: 'fir-demo-project-f6869',
    storageBucket: 'fir-demo-project-f6869.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQGGrJCswdxmitDjWonmNFe9QfIVRxsoo',
    appId: '1:8552136043:ios:7ebef9defe8968aad3a02e',
    messagingSenderId: '8552136043',
    projectId: 'fir-demo-project-f6869',
    storageBucket: 'fir-demo-project-f6869.appspot.com',
    iosBundleId: 'com.example.firebaseWithLoginProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQGGrJCswdxmitDjWonmNFe9QfIVRxsoo',
    appId: '1:8552136043:ios:7ebef9defe8968aad3a02e',
    messagingSenderId: '8552136043',
    projectId: 'fir-demo-project-f6869',
    storageBucket: 'fir-demo-project-f6869.appspot.com',
    iosBundleId: 'com.example.firebaseWithLoginProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRC7HV2jcyhPAvMuwbHv0zLNTg2QYakWA',
    appId: '1:8552136043:web:6c448c215fb86eefd3a02e',
    messagingSenderId: '8552136043',
    projectId: 'fir-demo-project-f6869',
    authDomain: 'fir-demo-project-f6869.firebaseapp.com',
    storageBucket: 'fir-demo-project-f6869.appspot.com',
  );
}
